# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8f9a8d83b79bc24979e98f72167fec2adda6769e6e26844257a1a2f2ecff29d9cd1941505a315f7e16d3193a181fc031a695cef963fc3f06fc6eb693fa49b9

test:
  secret_key_base: 53f07d31c070217b8e42cc4dd1bb512583ec2f3731947322f626daa07bfd3df1ed6a6ee6c6edc3d3bb797d976aae2ff126742eb4fa85345de7516b35bddb9677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
